### ISSUE TITLE
Element names

### ISSUE THREAD

**Issue by somexpert** [unt-libraries/untl-schemas#1]
@ldko and @damonkelley, are you guys ok with the name unix_file_output for the root element as opposed to UNIXFileOutput? I'm not much for camel-case when one of the words is fully capitalized. Also, as it currently stands, one of the child elements (<magicLocation>) uses camel-case and one (<mimetype>) does not. Should we make them both camel-case, use underscores, or leave them as-is?

**Comment by ldko** [comment]
`<xmlData>` and the rest of the METS record we happen to be putting this in at this time are camel case and our untl.xsd already uses camel case. I am going to vote based on these samples and one of the child elements already being camel case and https://msdn.microsoft.com/en-us/library/141e06ef(v=vs.71).aspx that we call it unixFileOutput.

**Comment by somexpert** [comment]
Well, that would definitely eliminate my objections to using camel-case. I can change `<mimetype>` to `<mimeType>` and use unixFileOutput as the root.

**Comment by ldko** [comment]
:+1:

**Comment by somexpert** [comment]
Changed `mimetype` to `mimeType` and `unix_file_output` to `unixFileOutput`.
